<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Отзывы");
?>
<? $APPLICATION->IncludeComponent(
                "travelsoft:travelsoft.news.list",
                "reviews",
                array(
                    "ACTIVE_DATE_FORMAT" => "d.m.Y",
                    "ADD_SECTIONS_CHAIN" => "N",
                    "AFP_106" => "",
                    "AFP_107" => "",
                    "AFP_108" => "",
                    "AFP_110" => "",
                    "AFP_113" => "",
                    "AFP_114" => "",
                    "AFP_116" => "",
                    "AFP_124" => "",
                    "AFP_125" => "",
                    "AFP_137" => "",
                    "AFP_197" => "",
                    "AFP_ID" => "",
                    "AFP_MAX_111" => "",
                    "AFP_MAX_112" => "",
                    "AFP_MAX_117" => "",
                    "AFP_MAX_130" => "",
                    "AFP_MIN_111" => "",
                    "AFP_MIN_112" => "",
                    "AFP_MIN_117" => "",
                    "AFP_MIN_130" => "",
                    "AJAX_MODE" => "N",
                    "AJAX_OPTION_ADDITIONAL" => "",
                    "AJAX_OPTION_HISTORY" => "N",
                    "AJAX_OPTION_JUMP" => "N",
                    "AJAX_OPTION_STYLE" => "N",
                    "CACHE_FILTER" => "N",
                    "CACHE_GROUPS" => "N",
                    "CACHE_TIME" => "36000000",
                    "CACHE_TYPE" => "A",
                    "CHECK_DATES" => "Y",
                    "COMPONENT_TEMPLATE" => "home_reviews",
                    "DESCRIPTION_LINK" => "/about/reviews/",
                    "DETAIL_URL" => "",
                    "DISPLAY_BOTTOM_PAGER" => "N",
                    "DISPLAY_DATE" => "Y",
                    "DISPLAY_NAME" => "Y",
                    "DISPLAY_PICTURE" => "Y",
                    "DISPLAY_PREVIEW_TEXT" => "Y",
                    "DISPLAY_TOP_PAGER" => "N",
                    "FIELD_CODE" => array(
                        0 => "NAME",
                        1 => "PREVIEW_TEXT",
                        2 => "DETAIL_TEXT",
                        3 => "SHOW_COUNTER",
                        4 => "DATE_CREATE",
                        5 => "",
                    ),
                    "FILTER_NAME" => "",
                    "HIDE_LINK_WHEN_NO_DETAIL" => "N",
                    "IBLOCK_ID" => "48",
                    "IBLOCK_TYPE" => "tsreviews",
                    "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
                    "INCLUDE_SUBSECTIONS" => "N",
                    "MESSAGE_404" => "",
                    "NEWS_COUNT" => "3",
                    "PAGER_BASE_LINK_ENABLE" => "N",
                    "PAGER_DESC_NUMBERING" => "N",
                    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
                    "PAGER_SHOW_ALL" => "N",
                    "PAGER_SHOW_ALWAYS" => "N",
                    "PAGER_TEMPLATE" => ".default",
                    "PAGER_TITLE" => "Блог",
                    "PARENT_SECTION" => "",
                    "PARENT_SECTION_CODE" => "",
                    "PREVIEW_TRUNCATE_LEN" => "",
                    "PROPERTY_CODE" => array(
                        0 => "LINK_ELEMENT_ID",
                        1 => "DESC",
                        2 => "PICTURES",
                        3 => "RATING",
                    ),
                    "SET_BROWSER_TITLE" => "N",
                    "SET_LAST_MODIFIED" => "N",
                    "SET_META_DESCRIPTION" => "N",
                    "SET_META_KEYWORDS" => "N",
                    "SET_STATUS_404" => "N",
                    "SET_TITLE" => "N",
                    "SHOW_404" => "N",
                    "SORT_BY1" => "TIMESTAMP_X",
                    "SORT_BY2" => "NAME",
                    "SORT_ORDER1" => "DESC",
                    "SORT_ORDER2" => "ASC",
                    "TEXT_DESCRIPTION" => "Все отзывы",
                    "TEXT_TITLE" => "Отзывы"
                ),
                false
            ); ?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>